=== LukeMcNemee/eszr-pb138/XMLs/Receipts_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="receipts">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="receipt" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="parts">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="part" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:all>
                                                  <xs:element name="ingredient">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="unit">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="ks"/>
                                                  <xs:enumeration value="lžička"/>
                                                  <xs:enumeration value="g"/>
                                                  <xs:enumeration value="kg"/>
                                                  <xs:enumeration value="špetka"/>
                                                  <xs:enumeration value="l"/>
                                                  <xs:enumeration value="ml"/>
                                                  <xs:enumeration value="dkg"/>
                                                  <xs:enumeration value="lžíce"/>
                                                  <xs:enumeration value="hrnek"/>
                                                  <xs:enumeration value="plechovka"/>
                                                  <xs:enumeration value="cl"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="amount">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:double">
                                                  <xs:minInclusive value="0"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LukeMcNemee/eszr-pb138/XMLs/Receipts_converted.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE receipts
  PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<receipts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Receipts_schema.xsd">
   <receipt>
      <name>Asijské kuře</name>
      <parts>
         <part>
            <ingredient>Kuřecí prsa</ingredient>
            <unit>kg</unit>
            <amount>0.5</amount>
         </part>
         <part>
            <ingredient>Solamyl</ingredient>
            <unit>ks</unit>
            <amount>1</amount>
         </part>
         <part>
            <ingredient>Sůl</ingredient>
            <unit>kg</unit>
            <amount>0.0005</amount>
         </part>
         <part>
            <ingredient>Kari</ingredient>
            <unit>kg</unit>
            <amount>0.0049504950495049506</amount>
         </part>
         <part>
            <ingredient>Pomerančová šťáva</ingredient>
            <unit>l</unit>
            <amount>0.03</amount>
         </part>
         <part>
            <ingredient>Citrónová šťáva</ingredient>
            <unit>l</unit>
            <amount>0.01</amount>
         </part>
         <part>
            <ingredient>Sójová omáčka</ingredient>
            <unit>l</unit>
            <amount>0.01</amount>
         </part>
         <part>
            <ingredient>Česnek</ingredient>
            <unit>ks</unit>
            <amount>1</amount>
         </part>
         <part>
            <ingredient>Zázvor</ingredient>
            <unit>ks</unit>
            <amount>1</amount>
         </part>
         <part>
            <ingredient>Cukr</ingredient>
            <unit>kg</unit>
            <amount>0.0005</amount>
         </part>
         <part>
            <ingredient>Jarní cibulka</ingredient>
            <unit>ks</unit>
            <amount>1</amount>
         </part>
      </parts>
   </receipt>
   <receipt>
      <name>Játrové řízečky</name>
      <parts>
         <part>
            <ingredient>Játrový salám</ingredient>
            <unit>kg</unit>
            <amount>0.3</amount>
         </part>
         <part>
            <ingredient>Mleté ořechy</ingredient>
            <unit>kg</unit>
            <amount>0.12</amount>
         </part>
         <part>
            <ingredient>Strouhanka</ingredient>
            <unit>kg</unit>
            <amount>0.08</amount>
         </part>
         <part>
            <ingredient>Mletá paprika</ingredient>
            <unit>kg</unit>
            <amount>0.0024752475247524753</amount>
         </part>
         <part>
            <ingredient>Sůl</ingredient>
            <unit>kg</unit>
            <amount>0.0005</amount>
         </part>
         <part>
            <ingredient>Vejce</ingredient>
            <unit>ks</unit>
            <amount>2</amount>
         </part>
         <part>
            <ingredient>Olej</ingredient>
            <unit>l</unit>
            <amount>0.1</amount>
         </part>
      </parts>
   </receipt>
   <receipt>
      <name>"Low Temperature" Roastbeef</name>
      <parts>
         <part>
            <ingredient>Hovězí roštěná</ingredient>
            <unit>kg</unit>
            <amount>0.75</amount>
         </part>
         <part>
            <ingredient>Máslo</ingredient>
            <unit>kg</unit>
            <amount>0.1</amount>
         </part>
         <part>
            <ingredient>Sůl</ingredient>
            <unit>kg</unit>
            <amount>0.0005</amount>
         </part>
         <part>
            <ingredient>Pepř</ingredient>
            <unit>kg</unit>
            <amount>0.0005</amount>
         </part>
         <part>
            <ingredient>Dijonská hořčice</ingredient>
            <unit>kg</unit>
            <amount>0.0049504950495049506</amount>
         </part>
         <part>
            <ingredient>Tymián</ingredient>
            <unit>kg</unit>
            <amount>0.0005</amount>
         </part>
      </parts>
   </receipt>
   <receipt>
      <name>Africké kari</name>
      <parts>
         <part>
            <ingredient>Kuře</ingredient>
            <unit>ks</unit>
            <amount>1</amount>
         </part>
         <part>
            <ingredient>Olivový olej</ingredient>
            <unit>l</unit>
            <amount>0.1</amount>
         </part>
         <part>
            <ingredient>Cibule</ingredient>
            <unit>ks</unit>
            <amount>1</amount>
         </part>
         <part>
            <ingredient>Česnek</ingredient>
            <unit>ks</unit>
            <amount>2</amount>
         </part>
         <part>
            <ingredient>Bobkový list</ingredient>
            <unit>ks</unit>
            <amount>1</amount>
         </part>
         <part>
            <ingredient>Rajčata oloupaná</ingredient>
            <unit>l</unit>
            <amount>0.4</amount>
         </part>
         <part>
            <ingredient>Kari</ingredient>
            <unit>kg</unit>
            <amount>0.009900990099009901</amount>
         </part>
         <part>
            <ingredient>Kokosové mléko</ingredient>
            <unit>l</unit>
            <amount>0.4</amount>
         </part>
         <part>
            <ingredient>Citron</ingredient>
            <unit>ks</unit>
            <amount>1</amount>
         </part>
      </parts>
   </receipt>
   <receipt>
      <name>Ajťácké Chilli con carne</name>
      <parts>
         <part>
            <ingredient>Červené fazole</ingredient>
            <unit>kg</unit>
            <amount>0.2</amount>
         </part>
         <part>
            <ingredient>Kukuřice</ingredient>
            <unit>kg</unit>
            <amount>0.1</amount>
         </part>
         <part>
            <ingredient>Hovězí maso</ingredient>
            <unit>kg</unit>
            <amount>0.45</amount>
         </part>
         <part>
            <ingredient>Rajčata</ingredient>
            <unit>ks</unit>
            <amount>3</amount>
         </part>
         <part>
            <ingredient>Cibule</ingredient>
            <unit>ks</unit>
            <amount>1</amount>
         </part>
         <part>
            <ingredient>Česnek</ingredient>
            <unit>ks</unit>
            <amount>4</amount>
         </part>
         <part>
            <ingredient>Chilli papričky</ingredient>
            <unit>ks</unit>
            <amount>1</amount>
         </part>
         <part>
            <ingredient>Vývar</ingredient>
            <unit>l</unit>
            <amount>0.2</amount>
         </part>
         <part>
            <ingredient>Polohrubá mouka</ingredient>
            <unit>kg</unit>
            <amount>0.4</amount>
         </part>
         <part>
            <ingredient>Olej</ingredient>
            <unit>l</unit>
            <amount>0.1</amount>
         </part>
         <part>
            <ingredient>Sůl</ingredient>
            <unit>kg</unit>
            <amount>0.0005</amount>
         </part>
         <part>
            <ingredient>Pepř</ingredient>
            <unit>kg</unit>
            <amount>0.0005</amount>
         </part>
         <part>
            <ingredient>Tymián</ingredient>
            <unit>kg</unit>
            <amount>0.0005</amount>
         </part>
      </parts>
   </receipt>
</receipts>

=== LukeMcNemee/eszr-pb138/src/main/resources/Receipts.xml
<?xml version="1.0" encoding="utf-8"?>

<receipts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="Receipts_schema.xsd">
  <receipt>
    <name>Asijské kuře</name>
    <parts>
      <part>
        <ingredient>Kuřecí prsa</ingredient>
        <unit>g</unit>
        <amount>500</amount>
      </part>
      <part>
        <ingredient>Solamyl</ingredient>
        <unit>ks</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Sůl</ingredient>
        <unit>špetka</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Kari</ingredient>
        <unit>lžička</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Pomerančová šťáva</ingredient>
        <unit>ml</unit>
        <amount>30</amount>
      </part>
      <part>
        <ingredient>Citrónová šťáva</ingredient>
        <unit>ml</unit>
        <amount>10</amount>
      </part>
      <part>
        <ingredient>Sójová omáčka</ingredient>
        <unit>ml</unit>
        <amount>10</amount>
      </part>
      <part>
        <ingredient>Česnek</ingredient>
        <unit>ks</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Zázvor</ingredient>
        <unit>ks</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Cukr</ingredient>
        <unit>špetka</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Jarní cibulka</ingredient>
        <unit>ks</unit>
        <amount>1</amount>
      </part>
    </parts>
  </receipt>

  <receipt>
    <name>Játrové řízečky</name>
    <parts>
      <part>
        <ingredient>Játrový salám</ingredient>
        <unit>g</unit>
        <amount>300</amount>
      </part>
      <part>
        <ingredient>Mleté ořechy</ingredient>
        <unit>g</unit>
        <amount>120</amount>
      </part>
      <part>
        <ingredient>Strouhanka</ingredient>
        <unit>g</unit>
        <amount>80</amount>
      </part>
      <part>
        <ingredient>Mletá paprika</ingredient>
        <unit>lžička</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Sůl</ingredient>
        <unit>špetka</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Vejce</ingredient>
        <unit>ks</unit>
        <amount>2</amount>
      </part>
      <part>
        <ingredient>Olej</ingredient>
        <unit>ml</unit>
        <amount>100</amount>
      </part>
    </parts>
  </receipt>

  <receipt>
    <name>"Low Temperature" Roastbeef</name>
    <parts>
      <part>
        <ingredient>Hovězí roštěná</ingredient>
        <unit>g</unit>
        <amount>750</amount>
      </part>
      <part>
        <ingredient>Máslo</ingredient>
        <unit>g</unit>
        <amount>100</amount>
      </part>
      <part>
        <ingredient>Sůl</ingredient>
        <unit>špetka</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Pepř</ingredient>
        <unit>špetka</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Dijonská hořčice</ingredient>
        <unit>lžička</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Tymián</ingredient>
        <unit>špetka</unit>
        <amount>1</amount>
      </part>
    </parts>
  </receipt>

  <receipt>
    <name>Africké kari</name>
    <parts>
      <part>
        <ingredient>Kuře</ingredient>
        <unit>ks</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Olivový olej</ingredient>
        <unit>ml</unit>
        <amount>100</amount>
      </part>
      <part>
        <ingredient>Cibule</ingredient>
        <unit>ks</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Česnek</ingredient>
        <unit>ks</unit>
        <amount>2</amount>
      </part>
      <part>
        <ingredient>Bobkový list</ingredient>
        <unit>ks</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Rajčata oloupaná</ingredient>
        <unit>plechovka</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Kari</ingredient>
        <unit>lžička</unit>
        <amount>2</amount>
      </part>
      <part>
        <ingredient>Kokosové mléko</ingredient>
        <unit>plechovka</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Citron</ingredient>
        <unit>ks</unit>
        <amount>1</amount>
      </part>
    </parts>
  </receipt>

  <receipt>
    <name>Ajťácké Chilli con carne</name>
    <parts>
      <part>
        <ingredient>Červené fazole</ingredient>
        <unit>g</unit>
        <amount>200</amount>
      </part>
      <part>
        <ingredient>Kukuřice</ingredient>
        <unit>g</unit>
        <amount>100</amount>
      </part>
      <part>
        <ingredient>Hovězí maso</ingredient>
        <unit>g</unit>
        <amount>450</amount>
      </part>
      <part>
        <ingredient>Rajčata</ingredient>
        <unit>ks</unit>
        <amount>3</amount>
      </part>
      <part>
        <ingredient>Cibule</ingredient>
        <unit>ks</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Česnek</ingredient>
        <unit>ks</unit>
        <amount>4</amount>
      </part>
      <part>
        <ingredient>Chilli papričky</ingredient>
        <unit>ks</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Vývar</ingredient>
        <unit>ml</unit>
        <amount>200</amount>
      </part>
      <part>
        <ingredient>Polohrubá mouka</ingredient>
        <unit>g</unit>
        <amount>400</amount>
      </part>
      <part>
        <ingredient>Olej</ingredient>
        <unit>ml</unit>
        <amount>100</amount>
      </part>
      <part>
        <ingredient>Sůl</ingredient>
        <unit>špetka</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Pepř</ingredient>
        <unit>špetka</unit>
        <amount>1</amount>
      </part>
      <part>
        <ingredient>Tymián</ingredient>
        <unit>špetka</unit>
        <amount>1</amount>
      </part>
    </parts>
  </receipt>
</receipts>
